### ISSUE TITLE
MS SQL Server Express (Database)

### ISSUE THREAD

**Issue by msbrown47** [wshahzad/Team-Four#1]
What version of MS SQL Server Express (Database) should be used for the project?

**Comment by wshahzad** [comment]
In visual studio 2013, when I created a web application and run it, the out
of box web app has a register user page when I register user it created a
db in App-data folder.  Which I then able to open in VS 2014, I m not sure
which version it was. It could be 2012 or 2015.
Please use latest one. And I will adjust my machine.

Waseem
Waseem

**Comment by msbrown47** [comment]
Hi Waseem,

Do you have a moment to meet via Google hangout?

thanks,

Marvin

---

On Sat, 5/23/15, wshahzad notifications@github.com wrote:

 Subject: Re: [Team-Four] MS SQL Server Express (Database) (#1)
 To: "wshahzad/Team-Four" Team-Four@noreply.github.com
 Cc: "msbrown47" marvin.sbrown@yahoo.com
 Date: Saturday, May 23, 2015, 7:03 AM

 In visual studio 2013, when I
 created a web application and run it, the out

 of box web app has a register user page when I register user
 it created a

 db in App-data folder.  Which I then able to open in VS
 2014, I m not sure

 which version it was. It could be 2012 or 2015.

 Please use latest one. And I will adjust my machine.

 Waseem

 Waseem

 On May 23, 2015 6:01 AM, "msbrown47"
 notifications@github.com wrote:

> What version of MS SQL Server Express (Database) should
>  be used for the
> 
> project?
> 
> —
> 
> Reply to this email directly or view it on GitHub
> 
>  https://github.com/wshahzad/Team-Four/issues/1.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by wshahzad** [comment]
Please call 973 255 9747

**Comment by wshahzad** [comment]
Marvin
I have also configured my machine with VS 2013 and MS SQL Server Express Edition.

Waseem
